### ISSUE TITLE
Does IBM recommend live and running IBP CA/Fabric CA in a well architected permissioned blockchain network? Please read on for the context

### ISSUE THREAD

**Issue by pvrbharg** [ibm-cloud-docs/blockchain#254]
Hello,

Context:

Customers are making statements - such as "Fabric CA or IBP CA components are not allowed into our Enterprise by our InfoSec"
Some blockchain practitioners are also making statements such as - "Fabric CA and IBP CA are not required since documentation says - OpenSSL can be used"

My personal opinion:
You cannot remove Fabric CA or IBP CA from the Hyperledger Blockchain Permissioned Network - Period.
You need Fabric CA or IBP CA in network - however these custom CAs can be made to work with customer Enterprise CAs or Well Known/Commercial/Public CAs
If you remove Fabric CA or IBP CA from network - you lose ability to be live, timely and inline. You could potentially lose some programming model capabilities and integrated functions such as [LDAP/AD integration, IdP integration, Extended Attributes, Affiliations, CID integration, HSM integration, IdMixer, ZKP, NodeJS SDK integration, Rest API wrapping capability of Fabric CA/IBP Ca and potentially broken defects from other components]. This is a point of time statement -as things stand today and exists today.

Interchangeable – IBM with Linux Foundation and Hyperledger Organization

Questions:
A) What is IBM's position on not having IBP CA in the blockchain network at all? Total removal of Fabric CA/IBM CA from network
B) What are the documented implications of not having a live, running Fabric / IBP CA?
C) Does IBM think - well architected and thriving Blockchain networks need capabilities beyond provisioning PKI?
D) Does IBM think - well architected and thriving Blockchain networks need capabilities of CA - live or out-of-band/non-live?
E) Does IBM think Fabric/IBP CA has same capabilities as OpenSSL or more capabilities than OpenSSL or less capabilities than OpenSSL?
F) If customers/IBMers insist on not having Fabric / IBM CA in the network - what capabilities still work and what capabilities do not work? Where is this documented?
G) If IBM ever tested a well architected and thriving Blockchain network that replaces Fabric CA/IBP CA with COTS vendor product CA?
H) If IBM has a customer reference that customers can speak to - for COTS Fabric CA/IBP CA deployment and risks/rewards
associated with such a deployment?
I) Would IBM recommend using 256 or 384 or 512 key size when using ECDSA curve?
J) Did IBM test with all three published key sizes or just tested with 256 key size for ECDSA curve encryption?

K) In the context of above questions – what is IBM’s stated support policy?

L) We need above answers publicly documented in IBP FAQ sections and I can help if needed. This would also help if we can document the same in Fabric and Fabric CA documentation repos/Github read-only documents

M) What are the implications from:
Vulnerability/penetration testing point of view and also from auditing and compliance point of view?
What are CSP responsibilities versus customers or service receivers?

Thanks.

**Comment by pvrbharg** [comment]
What if we get to the next comment indicated below here [fictitious and I HAVE NOT HEARD THIS STATEMENT - I AM MAKING UP]:

Customers making statements - such as "RAFT consensus or IBP consensus components are not allowed into our Enterprise by our Kafka/ZKP teams"
Some blockchain practitioners making statements such as - "RAFT consensus or IBP consensus components are not required since documentation says - OpenRAFT can be used [OpenRAFT is my invention and there is no such thing...]"

If you remove live CA or live consensus nodes from network and explain that everything can be done in offline or non-live or out-of-band mode - then well - why do we need anything live?

One of the tenets of well architected and well setup Blockchain network is - bounded time consensus resolution and growing the blockchain block height - so the committed transactions gets more trusted to be not changeable/tamper-evident.

Again all my opinions and we need to document clearly what is minimal and non-negotiable network components.

Thanks.

**Comment by pamandrejko** [comment]
@pvrbharg 
A) IBP fully supports using certificates from an external CA (one that is not created by the console or APIs or Fabric). 
This is documented here https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-adv-deployment#ibp-console-adv-deployment-third-party-ca

B) Also, if they choose to not have a CA in their console, then they are responsible for manually building an MSP and using that for their nodes and channels. That process is doc'd here: https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-organizations#console-organizations-build-msp. Also, customers are responsible for managing the certificate renewal: https://cloud.ibm.com/docs/blockchain?topic=blockchain-cert-mgmt

E) Does IBM think Fabric/IBP CA has same capabilities as OpenSSL or more capabilities than OpenSSL or less capabilities than OpenSSL? Fabric/IBP CA has more capabilities than OpenSSL because it generates the MSP (organization definition) for you. 

F) If customers/IBMers insist on not having Fabric / IBM CA in the network - what capabilities still work and what capabilities do not work? Where is this documented? Automatic certificate renewal is not available for certificates from an external CA. 
See Certificates from an external CA: under https://cloud.ibm.com/docs/blockchain?topic=blockchain-cert-mgmt#cert-mgmt-cert-types

I) Would IBM recommend using 256 or 384 or 512 key size when using ECDSA curve?
The default settings for security everywhere is P256 curve .... and is the recommended setting.
https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-security#ibp-security-ibp-keys

J) Did IBM test with all three published key sizes or just tested with 256 key size for ECDSA curve encryption?
Just P256.

K) In the context of above questions – what is IBM’s stated support policy? IBM Supports what IBP provides, so P256.

Recently there was an IBP Users Call that demonstrated this process:
https://event.on24.com/eventRegistration/EventLobbyServlet?target=reg20.jsp&referrer=&eventid=2440454&sessionid=1&key=C3E80E0B23FF85B3F96C7EC343132976&regTag=1114992&sourcepage=register

**Comment by pamandrejko** [comment]
Since we have now doc'd how to use certs from an external CA and an intermediate CA and created tutorials for that information, I am closing this issue. Feel free to open further issues if you think that additional actions need to be taken.

Using certs from an external CA: https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-tutorial-extca
Creating an intermediate Certificate Authority (CA): https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-ica

**Comment by pvrbharg** [comment]
@pamandrejko Dear Pam. Thank you and I am good. Best wishes.
