### ISSUE TITLE
Reference to IBM Cloud Private...

### ISSUE THREAD

**Issue by bobbiejc** [ibm-cloud-docs/blockchain#257]
This sentence is on our HA page: https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-ha

If you are using IBM Cloud Private, review the content about Implementing HA on IBM Cloud Private.

**Comment by pamandrejko** [comment]
Thanks @bobbiejc . That sentence is there because this repository contains the MultiCloud IBP4ICP documentation which uses IBM Cloud Private. To avoid confusion with our Software offering, we are actually in the process of removing that content to its own repository. Once that has occurred we can remove this sentence.

**Comment by nikhil550** [comment]
Thanks for bringing this our attention. I will remove this sentence from our docs.

**Comment by nikhil550** [comment]
Hey @bobbiejc @bobbiejc All instances of IBM Cloud private have been removed from this topic: https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-console-build-ha-ca

The whole repo has been cleansed of IBM Cloud private and multicloud references after moving those docs to their own repo.
