### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by irsanss** [ibm-cloud-docs/blockchain#268]
Documentation for the IBM Support for Hyperledger Fabric is a current IBM product offering; the [documentation is available at https://www.ibm.com/docs/en/hlf-support/1.0.0](https://www.ibm.com/docs/en/hlf-support/1.0.0).

1. The above link is not helpful or you are not providing the correct link
2. There is no migration steps.migration recommendation, help available from IBM cloud, impact to cloud credits for subscription user. Impact to support and SLA.

**Comment by altharp** [comment]
Migration tooling to migrate from IBM Blockchain Platform for IBM Cloud to IBM Support for Hyperledger Fabric was made available in the spring of 2023, a few months before end of support of IBM Blockchain Platform for IBM Cloud on July 31, 2023.  This gave customers a number of months to migrate and customers were able to migrate successfully and thus continue using IBM Cloud services like IBM Kubernetes Service.

The documentation for IBM Support for Hyperledger Fabric is available at https://www.ibm.com/docs/en/hlf-support/1.0.0.

The IBM Cloud documentation which this issue relates to has now been removed from public access at https://cloud.ibm.com/docs/blockchain.  I am closing this issue at this point since the subject documentation is no longer available.
